import type { Question } from '../context/QuizContext';

const GEMINI_API_KEY = "AIzaSyDQGBV8E43tZ9EG1x79YyZfmt5OCTD5Df4";

interface GeminiResponse {
  candidates: Array<{
    content: {
      parts: Array<{
        text: string;
      }>;
    };
  }>;
}

export class AIService {
  static async generateQuestions(topic: string): Promise<Question[]> {
    try {
      const prompt = `Generate 5 multiple choice questions with 4 options each on the topic: "${topic}". Provide the output as a JSON array with fields: question (string), options (array of strings), correctAnswer (index of correct option starting from 0).`;

      const response = await fetch(
        'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent',
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'X-goog-api-key': GEMINI_API_KEY,
          },
          body: JSON.stringify({
            contents: [
              {
                parts: [
                  {
                    text: prompt,
                  },
                ],
              },
            ],
          }),
        }
      );

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error?.message || 'Gemini API error');
      }

      const data: GeminiResponse = await response.json();
      const generatedText = data.candidates[0]?.content?.parts[0]?.text?.trim();

      if (!generatedText) {
        throw new Error('No response text from Gemini API');
      }

      // Extract JSON safely from generatedText (from first [ to last ])
      const startIndex = generatedText.indexOf('[');
      const endIndex = generatedText.lastIndexOf(']');
      if (startIndex === -1 || endIndex === -1 || endIndex <= startIndex) {
        throw new Error('JSON array not found properly in Gemini API response');
      }
      const jsonString = generatedText.substring(startIndex, endIndex + 1);

      const parsedQuestions = JSON.parse(jsonString) as Array<{
        question: string;
        options: string[];
        correctAnswer: number;
      }>;

      const questions: Question[] = parsedQuestions.map((q, idx) => ({
        id: idx + 1,
        question: q.question,
        options: q.options,
        correctAnswer: q.correctAnswer,
      }));

      return questions;
    } catch (error) {
      console.error('Error generating questions from Gemini API:', error);
      throw error;
    }
  }

  static async generateFeedback(score: number, totalQuestions: number, topic: string): Promise<string> {
    const prompt = `Provide a short, motivating feedback message for a user who scored ${score} out of ${totalQuestions} on the topic "${topic}". The message should be encouraging and customized based on their performance.`;
    try {
      const response = await fetch(
        'https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent',
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'X-goog-api-key': GEMINI_API_KEY,
          },
          body: JSON.stringify({
            contents: [
              {
                parts: [
                  { text: prompt }
                ]
              }
            ],
          }),
        }
      );

      if (!response.ok) {
        const errData = await response.json();
        throw new Error(errData.error?.message || 'Gemini API error while generating feedback');
      }

      const data = await response.json();
      const generatedText = data.candidates[0]?.content?.parts[0]?.text?.trim();

      if (!generatedText) {
        throw new Error('No feedback text generated by Gemini API');
      }

      return generatedText;
    } catch (error) {
      console.error('Error generating feedback from Gemini API:', error);
      // Optional fallback, you can also re-throw to display error upstream
      return `You scored ${score}/${totalQuestions} on ${topic}. Keep practicing to improve!`;
    }
  }
}
